;;; quotes.el --- Quote of the Day for Doom Dashboard -*- lexical-binding: t; -*-

;; Display a daily rotating quote on the Doom Emacs dashboard.
;; Quotes are loaded from quotes.json generated by scripts/scrape-quotes.py

;;; Code:

(require 'json)

(defvar my/quotes-file (expand-file-name "quotes.json" doom-user-dir)
  "Path to the quotes JSON file.")

(defvar my/quotes-cache nil
  "Cached quotes data from JSON file.")

(defvar my/quotes-width 70
  "Maximum width for word-wrapping quotes.")

(defun my/quotes-load ()
  "Load quotes from JSON file, caching the result."
  (unless my/quotes-cache
    (when (file-exists-p my/quotes-file)
      (condition-case err
          (let* ((json-object-type 'plist)
                 (json-array-type 'list)
                 (data (json-read-file my/quotes-file)))
            (setq my/quotes-cache (plist-get data :quotes)))
        (error
         (message "Error loading quotes: %s" err)
         nil))))
  my/quotes-cache)

(defun my/quotes-get-today ()
  "Get today's quote, deterministically selected by date."
  (let ((quotes (my/quotes-load)))
    (when (and quotes (> (length quotes) 0))
      (let* ((days-since-epoch (/ (float-time) 86400))
             (index (mod (floor days-since-epoch) (length quotes))))
        (nth index quotes)))))

(defun my/quotes-wrap-text (text width)
  "Wrap TEXT to fit within WIDTH characters, returning list of lines."
  (let ((words (split-string text))
        (lines nil)
        (current-line ""))
    (dolist (word words)
      (let ((test-line (if (string-empty-p current-line)
                           word
                         (concat current-line " " word))))
        (if (<= (length test-line) width)
            (setq current-line test-line)
          ;; Line would be too long, start a new one
          (when (not (string-empty-p current-line))
            (push current-line lines))
          (setq current-line word))))
    ;; Don't forget the last line
    (when (not (string-empty-p current-line))
      (push current-line lines))
    (nreverse lines)))

(defun my/quotes-format-quote (quote-data)
  "Format QUOTE-DATA plist into display string."
  (let* ((text (plist-get quote-data :quote))
         (author (plist-get quote-data :author))
         (source (plist-get quote-data :source))
         (translated-from (plist-get quote-data :translated_from))
         (wrapped-lines (my/quotes-wrap-text text my/quotes-width))
         (attribution (concat
                       (format "-- %s" author)
                       (when source (format ", %s" source))
                       (when translated-from (format " [trans. from %s]" translated-from)))))
    ;; Build the formatted quote
    (concat
     ;; Quote text with opening quote mark
     (mapconcat
      (lambda (line)
        (concat "\"" line))
      (list (car wrapped-lines))
      "")
     ;; Continuation lines (if any)
     (if (cdr wrapped-lines)
         (concat "\n"
                 (mapconcat
                  (lambda (line)
                    (concat " " line))
                  (cdr wrapped-lines)
                  "\n")
                 "\"")
       "\"")
     "\n\n"
     ;; Attribution, right-aligned
     (make-string (max 0 (- my/quotes-width (length attribution) 4)) ?\s)
     attribution)))

(defun my/doom-dashboard-widget-quote ()
  "Insert quote of the day widget into dashboard."
  (let ((quote-data (my/quotes-get-today)))
    (if quote-data
        (let* ((formatted (my/quotes-format-quote quote-data))
               (lines (split-string formatted "\n")))
          ;; Insert header
          (insert "\n")
          (insert (+doom-dashboard--center
                   +doom-dashboard--width
                   (propertize "Quote of the Day"
                               'face '(:foreground "#5B6268" :slant italic))))
          (insert "\n\n")
          ;; Insert each line of the quote, centered
          (dolist (line lines)
            (insert (+doom-dashboard--center
                     +doom-dashboard--width
                     (propertize line 'face '(:foreground "#5B6268"))))
            (insert "\n"))
          (insert "\n"))
      ;; Fallback if no quotes available
      (insert "\n")
      (insert (+doom-dashboard--center
               +doom-dashboard--width
               (propertize "No quotes available. Run scripts/scrape-quotes.py"
                           'face '(:foreground "#5B6268" :slant italic))))
      (insert "\n\n"))))

(provide 'quotes)
;;; quotes.el ends here
